// src/pages/Post.tsx
import { ProcessedPost } from 'content:routes';
import { Head } from '../components/Head';
import { PostMeta } from '../components/PostMeta';
import { TableOfContents } from '../components/TableOfContents';
import { useLazyPost } from '../hooks/useLazyPost';

export const Post = ({
  path,
  load,
}: {
  path: string;
  load: () => Promise<ProcessedPost>;
}) => {
  const post = useLazyPost(path, load);
  const title = post.title;

  return (
    <div className="xl:flex xl:justify-center">
      <Head title={`${title} | gadgetlunatic`} path={path} />
      <div className="container md:mx-auto xl:mx-0 max-w-4xl box-content flex-none">
        <div className="px-4">
          <header>
            <h1 className="font-bold text-3xl my-8">{title}</h1>
            <div className="my-8">
              <PostMeta
                date={post.date}
                permalink={post.permalink}
                modifiedDate={post.modifiedDate}
                hash={post.hash}
              />
            </div>
          </header>
          <article className="prose mb-16 max-w-none prose-slate">
            {post.element}
          </article>
        </div>
      </div>
      <div className="hidden xl:block flex-none w-72">
        <div className="p-4 sticky mt-40 inset-0 max-h-screen overflow-y-scroll">
          <TableOfContents headings={post.headings} />
        </div>
      </div>
    </div>
  );
};

// .vitepress/theme/Post.vue
<script setup lang="ts">
import { useData } from 'vitepress';
import TableOfContents from './TableOfContents.vue';
import PostMetaData from './PostMetaData.vue';

const { frontmatter } = useData();
</script>
<template>
  <div class="xl:flex xl:justify-center">
    <div class="container md:mx-auto xl:mx-0 max-w-2xl box-content flex-none">
      <div class="px-4">
        <header>
          <h1 class="font-bold text-2xl my-8">{{ frontmatter.title }}</h1>
          <div class="my-8">
            <PostMetaData
              :date="frontmatter.date"
              :modified-date="frontmatter.modifiedDate"
              :permalink="frontmatter.permalink"
              :hash="frontmatter.hash"
            />
          </div>
        </header>
        <article class="prose mb-16 max-w-none prose-slate">
          <Content />
        </article>
      </div>
    </div>
    <div class="hidden xl:block flex-none w-72">
      <div class="p-4 sticky mt-40 inset-0 max-h-screen overflow-y-scroll">
        <TableOfContents />
      </div>
    </div>
  </div>
</template>
